# Generated by Django 2.2.9 on 2020-02-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPAC_app', '0002_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Book', 'Book'), ('Artical', 'Artical'), ('Digital', 'Digital'), ('Journal', 'Journal')], max_length=10),
        ),
    ]
