# Generated by Django 2.2.9 on 2020-02-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OPAC_app', '0004_borrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['due_date']},
        ),
    ]
